Developer 1
Faner201/medical_shedule pull request #2
Opened 2022-10-07 11:59 UTC by Faner201

2022-10-07 12:10 UTC, Vixorem commented
Ты уверен, что не забыл гит игнор? Кажется, что очень много всякой фигни, типа папки obj

2022-10-07 12:11 UTC, Vixorem requested changes

2022-10-07 12:11 UTC, Vixorem commented on Entity/Entities/User.cs
> +    public AccountRole Role { get => _role; set => _role = value; }
Почитай про autoproperty/автосвойства в шарпах

2022-10-07 12:11 UTC, Vixorem commented on Entity/Repository/IRepository.cs
> + public interface IRepository<T> : IDisposable
Почему диспоузбл?

2022-10-07 12:11 UTC, Vixorem commented on Entity/Repository/SQLUserRepository.cs
> +{
Далековато забежал) достаточно было пока только на абстракциях выполнить задания; никто ведь даже не говорил, что база будет sqlная)

2022-10-07 12:11 UTC, Vixorem commented on Entity/UserService.cs
> +    private  IUserRepository _db = new SQLUserRepository();
А вот тут прям принципиально неправильно. Ты в сервисе, то есть в бизнес логике, достаешь конкретную реализацию репозитория

Советую прочитать про инверсию зависимости / dependency inversion

2022-10-07 12:16 UTC, DeadDogDance commented on XUnit-test/UnitTest1.cs
> +        public void CreateNewUserWithEmptyLogin_ShoudFail()
пропустил L в "shou'l'd_fail"

2022-10-07 13:23 UTC, Faner201 commented on Entity/Repository/SQLUserRepository.cs
> +{
))))))))

2022-10-07 13:38 UTC, Faner201 commented on Entity/Repository/IRepository.cs
> + public interface IRepository<T> : IDisposable
А, как я могу предположить, он освобождает неуправляемые ресурсы. Тем самым, у наследуемого класса, с реализацией уже этих виртуальных методов, если будет происходит тот же цикл в запросе к бд, то он по сути его удалит из памяти.

2022-10-07 13:45 UTC, Faner201 commented on Entity/Repository/SQLUserRepository.cs
> +{
Просто толком не поняв тз, я что то полетел реализовывать деталь этого продукта(

2022-10-08 10:22 UTC, DeadDogDance approved these changes
Approved

2022-10-08 10:26 UTC, Vixorem approved these changes

2022-10-08 10:26 UTC, Vixorem commented on Entity/UserService.cs
> +            phoneNumber: string.Empty,
Странно ведь как то, метод называется создать юзера, а прокидывается только логин, а остальное дефолтное

2022-10-08 10:27 UTC, Vixorem approved these changes

2022-10-08 10:46 UTC, merged