Developer 3
Faner201/medical_shedule pull request #4
Opened 2022-11-07 13:44 UTC by Faner201

2022-11-07 13:58 UTC, Vixorem requested changes

2022-11-07 13:58 UTC, Vixorem commented on Database/DoctorModelService.cs
> +        return new List<Doctor>(new Doctor {
А это билдится? Просто по идее реквест это список, а ниже вы с ним работаете как с одним объектом

2022-11-07 13:58 UTC, Vixorem commented on Database/DoctorModelService.cs
> +        var request = _db.Doctor.FirstOrDefault(u => u.Specialization == specialization);
А тут нам нужоо получить список, поэтому FistOrDefault не подходит 
Используйте where, и потом сделайте .ToList()

2022-11-07 13:58 UTC, Vixorem commented on Database/ReceptionModelService.cs
> +    public Reception SaveDoctorAppointment(DateTime date, int doctorID)
Мне кажется, что будет проще, если в метод будет передаваться объект ресепшн,у объекта как раз и начало и конец же есть

2022-11-07 13:58 UTC, Vixorem commented on Database/ReceptionModelService.cs
> +    public List<DateTime> GetFreeAppointmentDateList(Specialization specialization)
Мне кажется, что этот метод надо делать на уровне сервиса, а не репы
Типа, получить все занятые аппойнтменты докторов указанной специализации
И потом вернуть даты, которые не пересекают эти занятые аппойнтменты

2022-11-07 13:58 UTC, Vixorem commented on Database/ScheduleModelService.cs
> +            _db.Schedule.Update(request);
СейвЧейнджес()

2022-11-07 13:58 UTC, Vixorem commented on Entity/ReceptionService.cs
> +    private IReceptionRepository _receptionService;
Ну по идее репозитоорий а не сервис

2022-11-09 11:55 UTC, fs-anvr commented on Database/ReceptionModelService.cs
> +    public List<DateTime> GetFreeAppointmentDateList(Specialization specialization)
Какой диапазон значений возвращать?. Все незанятые - бесконечное множество

2022-11-20 15:53 UTC, closed without merging